### ISSUE TITLE
Periodic jobs

### ISSUE THREAD

**Issue by kraih** [kraih/minion#24]
It appears that there's a lot of interest in periodic jobs, and i think native support in Minion would make sense. Many existing implementations appear to be using a single server, often backed by cron, to schedule their periodic jobs. It has been suggested that cron+unique jobs (as proposed in #22) would be good enough, but i'm not so sure about that. What do you think, can we come up with something better?

**Comment by kraih** [comment]
Only dealing with unique jobs internally and letting cron handle the scheduling, does have the advantage that we don't have to care about testing.

**Comment by s1037989** [comment]
I am extremely interested in not having scheduled / periodic jobs in cron.  One great use case might be a website that offers a service which needs to do routine actions on behalf of its users and therefore requires cron jobs.  But do you really want your website creating cron jobs?  Sure, it can work, but it would work and feel so much better being all integrated as part of the framework.

How does cron work?  Does it check for jobs every minute even if there are no jobs?  Minion, with it's Mojo::IO::Loop backend, could do the same, checking every minute to see what's scheduled and then run the necessary jobs.  There would of course have to be a DSL that allows for definition of the desired schedule and frequency, but once that's defined and understood how to parse, everything else is just running the tasks at the specified time.

Anyway, I'm totally in favor!  Would love to help but doubt that I can...  :(

**Comment by djgoku** [comment]
I built a Job Scheduler at work that uses [croniter](https://github.com/kiorky/croniter), postgresql, and gearman.

The job scheduler scans the database jobs schedule (4000 schedules now which isn't ideal) able looking for things that need to be scheduled.

For each scheduled job we create a unique job id that can only be re-used for scheduled jobs. Since we wanted the ability to re-try a configurable amount of times. We have a job status table which (uses the unique job id as a fk) we use to see how many times a job has been re-run. We also create a unique job id for adhoc jobs, but they will only have a few statuses in our statuses table vs scheduled jobs that fail may have a lot more compared to adhoc if they are failing.

We will never have duplicate calls added to the queue since gearman supports that out of the box:
`Gearman performs coalescence on the work sent by a client. If two or more clients ask for work to be completed on the same body of work, either by seeing that the same blocks are being sent or by using the unique value sent by the client, it will coalesce the work so that only one worker is used. It does this specifically to avoid thundering herd problems which are common to cache hit failures.` from https://en.wikipedia.org/wiki/Gearman

Not sure if this will help at all. But I thought I would share some of my experiences.

**Comment by scottw** [comment]
I have a friend who would love to get away from using cron for scheduling. They are trying to build a billing system component for recurring transactions. As it stands, the do a big fat DB query via cron every minute/hour/day to see what might be due and then run it. I'm not sure if this is the right use case for him, but am intrigued by the possibility of native minion without cron.

**Comment by kraih** [comment]
Minion being a distributed system makes this a really hard problem to solve. You don't want all workers in the cluster try to reschedule jobs at the same time. So you basically need an election process, where one worker becomes the scheduler. And the election process needs to be repeated when the elected worker disappears from the cluster again. This would be a lot of work to get right.

**Comment by borisbaldassari** [comment]
The periodic job feature would be great. => +1
But as others pointed out I would vote for _not relying on a system cron_ for that. Mainly because of portability (e.g. what about windows?).
Also reusing cron-like syntax (not another dsl please) would be great, since it's widely known and most people are comfortable with it

**Comment by keenlinks** [comment]
I currently use cron with curl to hit my app through https, where the controller of the matched route then enqueues the minion job. Cron is currently configurable to me and this works well and is pretty simple. However, is cron available on many PaaS and SaaS hosting platforms which promote developer friendly setups (cron may be viewed as not a part of a stack and a sysadmin tool)? If not, I would like to see the scheduling within Minion for the developer to control through the app.

**Comment by vikasnkumar** [comment]
The cron + unique job issues need to be separated out since I feel they're separate problems:

- **On Using cron**: Cron is limited to Unix-like systems and also is limited to a minute level resolution. This can be severely limiting if your jobs need only say 5-10 seconds to run and you're waiting for the minute to complete before you can run the next set of jobs. This may or will lead to the system being idle at times or if too many jobs are scheduled for the same minute, then overloaded at the same time. I am not sure whether rolling a new daemon is the right solution, but it should be easy enough with AnyEvent for prototyping. This can allow jobs to run on wall-clock time and also on their own on arbitrary periods.

- **On Unique Jobs**: What is defined as a _unique_ job ? How does Minion know whether a job is unique or not ? Isn't this context/application specific ? If a particular job has to be unique, in my opinion, the user should make sure that the job is consistent with being unique by using the database backend. For example, if the user schedules a job twice and it needs to run only once, whichever scheduled job runs first, can set a flag in the db stating it is running and the other job doesn't run. The onus should be on the job to check this flag before running.

**Comment by kraih** [comment]
I guess it might be worth mentioning #7, which first brought up the unique job topic and describes a possible implementation best.

**Comment by kraih** [comment]
I'm really interested in how other popular job queues have solved this problem, so if you see a solution, please post a link! I'll start with Sidekiq, which appears to support periodic jobs in its commercial version. https://github.com/mperham/sidekiq/wiki/Ent-Periodic-Jobs

**Comment by vikasnkumar** [comment]
[SLURM](https://computing.llnl.gov/linux/slurm/) is a popular scheduler in the High Performance Computing space and tools like Sidekiq fall short of Slurm's overall capabilities like checkpointing, binding CPUs to jobs, etc.. Slurm's [srun](https://computing.llnl.gov/linux/slurm/srun.html) command supports scheduling jobs at fixed times with seconds level granularity unlike cron which is minute level.

**Comment by kraih** [comment]
Celery uses a separate (centralized) daemon to schedule periodic jobs. http://docs.celeryproject.org/en/master/userguide/periodic-tasks.html

**Comment by kraih** [comment]
Resque does the same. https://github.com/resque/resque-scheduler

**Comment by kraih** [comment]
Getting the feeling that maybe the job scheduler shouldn't be part of Minion itself, but a separate CPAN module.

**Comment by kraih** [comment]
I've not actually seen this anywhere yet, but i think periodic jobs could also work like retries. The `minion_jobs` table gets a new column `recurring`, which signals that the job should be repeated and contains information on when that job is supposed to run again. And whenever a job with `recurring` value transitions to the state `finished`, a new job with the same attributes gets enqueued automatically.
```
$minion->enqueue(some_hourly_job => [@args] => {recurring => '0 * * * * *'});
```
This would have a lot of advantages, exceptions and retries just work, these jobs would have the same lifecyle as every other job. But we would also need a way to stop these recurring jobs again, since the data persists in the database, they have to be stopped manually.

**Comment by kraih** [comment]
Another problem with this approach might be that there's a small window after the previous job transitioned to `finished`, during which the worker can crash and prevent the followup job from being enqueued. For retries this is not as important, since those jobs would just stay `failed`, but here the previous job is `finished` and can therefore get lost easily.

**Comment by kraih** [comment]
There are solutions though, we could just not let jobs with a `recurring` value transition to `finished`, and reset them to `inactive` directly. This would also help with removing recurring jobs again actually. Because now there could be a sync process, where each worker has a list of recurring jobs during startup and ensures that those are the only recurring jobs in the queue.
```
$minion->schedule(some_hourly_job    => '0 * * * *' => [@args] => {retries => 3});
$minion->schedule(another_hourly_job => '0 * * * *' => [@args]);
```

**Comment by avkhozov** [comment]
I might see a problems with the solution using new recurring column:
1. If the minion worker crashing, that the new periodic jobs would be enqueueing after ``minion_after`` seconds only, not on the schedule.
2. If the job takes longer than scheduling period, that new job would be enqueueing in invalid time. For example, job needs to be enqueued every minute, but sometimes it performed more than one minute.

**Comment by kraih** [comment]
@avkhozov I don't think there are any existing solutions with a higher level of accuracy.

**Comment by avkhozov** [comment]
I like solution with election a master worker. For example, every ``heartbeat-interval`` minion backend will elect new master worker (in ``register_worker`` method) through some algorithm and store flag ``is_master`` in backend database. While enqueuing the new periodic job from worker we can pass new ``master`` option to enqueue method and job will be enqueued only if master id in options equal current master in backend database. So all minion workers will be do ``$minion->enqueue(task => [@args] => {%$options, master => $workek->id})`` by schedule, but only one job will be really enqueued. And while we have at least one minion worker in cluster we can properly enqueue periodic jobs.

**Comment by brianmed** [comment]
https://github.com/kraih/minion/compare/master...brianmed:elected_recurring

Any thoughts on this code?

**Comment by kraih** [comment]
Recurring jobs could also be used for queue maintenance with `Minion::repair`. Which currently runs inside the main process and might therefore cause delays for job processing.

**Comment by kraih** [comment]
Ok, after thinking about this some more i believe that a complicated solution is not right for us. Instead we will focus on making Minion work better with cron. That means possibly adding a unique jobs feature if we can find a good enough solution.

**Comment by kraih** [comment]
Now that we have job dependencies, the old way of doing unique jobs has become much less interesting though. At the moment i can only really see expiring locks working there.
```
app->minion->add_task(some_task => sub {
  my ($job, @args) = @_;

  # Try to get the lock for up to 20 minutes (then it expires)
  return $job->finish('Another job already in progress for some_unique_key')
    unless $job->try_to_lock('some_unique_key', '20 minutes');

  ... do stuff ...

  # Release the lock in this job or a followup job (for job dependencies)
  $job->release_lock('some_unique_key');
});
```

**Comment by kraih** [comment]
I've been experimenting a bit with exclusive and shared locks. https://github.com/kraih/minion/compare/expiring_locks Sadly the shared lock part didn't work out too well, since on a busy queue a missing unlock might never resolve itself again, resulting in wasted resources. Maybe someone else has a better idea for how to do it.

**Comment by kraih** [comment]
Closing this issue, since from now on our priority will just be to make Minion work better with cron. Lets wait and see what features our users can come up with to make that happen.

**Comment by avkhozov** [comment]
@kraih I see a concurrency problem in current `minion_lock` function. Two or more queries can be executed simultaneously. We can get the `unique_violation` exception while `insert` or `holders` can be `>= $3` while `update`.

What about using `upsert` for this case?

```sql
create function minion_lock(text, int, int) returns bool as $$
declare
  new_expires timestamp with time zone = now() + (interval '1 second' * $2);
  lock record;
begin
  delete from minion_locks where expires < now() or holders <= 0;
  insert into minion_locks as l values ($1, 1, new_expires)
    on conflict (name) do update
    set holders = l.holders + 1, expires = greatest(l.expires, new_expires)
    where l.holders < $3;
  return found;
end;
$$ language plpgsql;
```

Also you can simplify `minion_unlock`:

```sql
create function minion_unlock(text) returns bool as $$
declare
  new_holders int;
begin
  delete from minion_locks where name = $1 and holders <= 0;
  update minion_locks set holders = holders - 1 where name = $1 returning holders into new_holders;
  return found and new_holders >= 0;
end;
$$ language plpgsql;
```

**Comment by kraih** [comment]
@avkhozov I don't think it makes sense trying to salvage that code, it is conceptually broken, shared locks just can't be done that way.

**Comment by kraih** [comment]
Forgot to update this issue, we now have support for expiring locks. http://mojolicious.org/perldoc/Minion#lock
